version: '3'

services:
  xraytv:
    image: bestzwei/xraytv:latest
    container_name: xraytv
    ports:
      - "8899:80"
    environment:
      - PASSWORD=your_password_here  # 设置密码保护，留空则不启用密码
      # 可以添加其他环境变量
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - xraytv-network

networks:
  xraytv-network:
    driver: bridge